[project]
name = "mongodb-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.2",
    "flask-marshmallow>=1.4.0",
    "marshmallow>=4.2.2",
    "pika>=1.3.2",
    "pymongo>=4.16.0",
]
